### PR TITLE
Change SIG lead dorbin --> aimeeu

### PR DESCRIPTION
**Pull request by dorbin**

### CODE REVIEW

**Comment by dorbin** [comment]
@aimeeu

**Comment by brian-armory** [comment]
+1 to adding Aimee as the leader. Once we find a another suitable lead, I will cede my seat so that the leadership for the SIG isn't two people from one company.

**Comment by aimeeu** [comment]
While Dave Dorbin can never truly be replaced, I'm happy to step into this SIG role. In 2019, I worked closely with a K9s Docs SIG Lead while I was under contract to the CNCF. Prior to that, I was the Docs Project Team Lead for Acumos (an LF project).  I'm currently a TW at Armory.

**Comment by ajordens** [comment]
TOC +1

Seeing as how @aimeeu is onboard, I'll merge.

**Pull request merged**
