### PR TITLE
chore(aws): SIG Lead change proposal for AWS

### PR DESCRIPTION
**Pull request by imosquera**
I'd like to propose Akshay Dayal to be SIG lead for AWS instead of myself.  Akshay has done a wonderful job of helping to organize, demos and agenda for the SIG lead for the last 2 meetings.

### CODE REVIEW

**Comment by robzienert** [comment]
Would like @jeyrschabu and @clareliguori to pop in and confirm this is known on the PR before merging.

**Comment by clareliguori** [comment]
Yep, I support

**Comment by jeyrschabu** [comment]
+1

**Comment by akshayabd** [comment]
Hey everyone, I'm excited to be a part of this going forward! Thanks Isaac for bringing me into this amazing group.

**Comment by ajordens** [comment]
Direction from @aglover is that SC approval is not needed for SIG Lead changes ... merging this.

**Pull request merged**
