### PR TITLE
Add a new Google SIG

### PR DESCRIPTION
**Pull request by plumpy**
I not ashamed to admit that I mostly copied this from the AWS SIG. Okay, I'm a little ashamed.

I'll fill in the meeting time, place, and doc in a follow-up PR after this is approved.

### CODE REVIEW

**Review by skandragon — APPROVED** [review]
LGTM.  Note I'm one of the listed leads.

**Comment by duftler** [comment]
(SC) LGTM.

**Comment by ajordens** [comment]
LGTM

**Comment by Nirmalyasen** [comment]
Looking forward to be part of this SIG.

**Comment by pauljrob** [comment]
(SC) LGTM

**Comment by plumpy** [comment]
@imosquera @emagana @pstout I'd love your vote on this proposal when you get a chance. Thanks!

**Comment by emagana** [comment]
Shouldn't this be call GCP SIG instead of Google? We have the AWS SIG not the Amazon one. IMHO

**Review by emagana — CHANGES_REQUESTED** [review]
Change the references from Google to GCP

**Comment by plumpy** [comment]
Fair enough. Although apparently we are no longer calling it GCP, it's just Google Cloud now. (Which I had sort of forgotten about... so I removed all references to "GCP" from the doc too.)

I moved the directory to `sig-googlecloud` for parity with `sig-tencentcloud` and `sig-yandexcloud`.

**Review by emagana — APPROVED** [review]
Thank you for the changes!

**Comment by emagana** [comment]
Welcome to the new Spinnaker SIG!

**Pull request merged**
